#!/bin/bash
#PBS -q sandy
#PBS -l nodes=1:ppn=16
#PBS -l walltime=10:00:00
#PBS -o output.out
#PBS -e output.err
module unload intel/15.0.6
module load intel/15.0.2
module load python/3.5.1
module load use.own
module load biopython/1.70

cd $PBS_O_WORKDIR
(python alignment_junction.py 50_forward.txt 50_reverse.txt 50_align2_logging.txt>>50_alignment_original2.csv)&
wait
